server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/connect
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  application:
    name: "cards"
  config:
    import: "configserver:http://localhost:8071"
  profiles:
    active: "prod"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probe:
        enabled: true

  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "cards"
    description: "Eazy Bank Cards Application"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        cards: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindow: 10
      permittedNumberOfCallInHalfOpenState: 2
      failureThreshold: 50
      waitDurationInOpenState: 10000

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 500
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      ignoreException:
        - java.lang.NullPointerException
      retryException:
        - java.util.concurrent.TimeoutException

resilience4j.ratelimiter:
  configs:
    default:
      timeoutDuration: 100
      limitRefreshPeriod: 5000
      limitForPeriod: 1