spring:
  application:
    name: "gatewayserver"
  config:
    import: "configserver:http://localhost:8071"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway server Application"
    version: "1.0.0"

logging:
  level:
    com: DEBUG
