server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/connect
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  sql:
    init:
      mode: always

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  
  application:
    name: "accounts"
  profiles:
    active: "prod"
  config:
    import: "configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "accounts"
    description: "Eazy Bank Accounts Application"
    version: "1.0.0"
